
spring:
  application:
    name: principal
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  security:
    user:
      name: user
      password: password
      roles: USERS
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081