spring:
  application:
    name: microUsuario
  datasource:
    url: jdbc:postgresql://localhost:5432/AtividadeMicroServico
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
server:
  port: 8090